ROLES = {
    'СБ':{'Job:Brigmedic',
    'Job:Detective',
    'Job:HeadOfSecurity',
    'Job:SecurityCadet',
    'Job:SecurityOfficer',
    'Job:SecurityPilot',
    'Job:SeniorOfficer',
    'Job:Warden',},

    'Командование':{'Job:Captain',
    'Job:ChiefEngineer',
    'Job:ChiefMedicalOfficer',
    'Job:HeadOfPersonnel',
    'Job:HeadOfSecurity',
    'Job:Quartermaster',
    'Job:ResearchDirector',
    'Job:BlueShieldOfficer',},

    'ИИ':{'Job:Borg',
    'Job:BorgSecurity',
    'Job:StationAI',},

    'Медицинский':{'Job:Chemist',
    'Job:ChiefMedicalOfficer',
    'Job:Coroner',
    'Job:MedicalDoctor',
    'Job:MedicalIntern',
    'Job:MedicalSurgeon',
    'Job:Paramedic',
    'Job:Psychologist',
    'Job:SeniorPhysician',},

    'ЦК':{'Job:CentralCommandAdministrator',
    'Job:CentralCommandOfficer',
    'Job:CentralCommandOfficial',
    'Job:CentralCommandOperator',
    'Job:CentralCommandSpecialOperationsOfficer',
    'Job:DeathSquad',
    'Job:ERTEngineerAmber',
    'Job:ERTEngineerGamma',
    'Job:ERTEngineerRed',
    'Job:ERTJanitorAmber',
    'Job:ERTJanitorGamma',
    'Job:ERTJanitorRed',
    'Job:ERTLeaderAmber',
    'Job:ERTLeaderGamma',
    'Job:ERTLeaderRed',
    'Job:ERTMedicalAmber',
    'Job:ERTMedicalGamma',
    'Job:ERTMedicalRed',
    'Job:ERTSecurityAmber',
    'Job:ERTSecurityGamma',
    'Job:ERTSecurityRed',
    'Job:Magistrat',
    'Job:CBURNAgent',
    'Job:CBURNLeader',},
    
    'Карго':{'Job:CargoTechnician',
    'Job:Quartermaster',
    'Job:SalvageSpecialist',
    'Job:SeniorSalvageSpecialist',
    },
    'Сервис':{'Job:Bartender',
    'Job:Botanist',
    'Job:Boxer',
    'Job:Chaplain',
    'Job:Chef',
    'Job:Clown',
    'Job:HeadOfPersonnel',
    'Job:Janitor',
    'Job:Librarian',
    'Job:Mime',
    'Job:Musician',
    'Job:Passenger',
    'Job:Reporter',
    'Job:Visitor',
    'Job:Zookeeper',
    'Job:ServiceWorker',
    'Job:ClownSponsor',
    'Job:SeniorAdministrator',},
    
    'Научный':{'Job:ResearchDirector',
    'Job:Scientist',
    'Job:ResearchAssistant',
    'Job:SeniorResearcher'},
    
    'Инженерный':{'Job:AtmosphericTechnician',
    'Job:ChiefEngineer',
    'Job:StationEngineer',
    'Job:TechnicalAssistant',
    'Job:SeniorEngineer',},
    
    'Юридический':{'Job:Magistrat',
    'Job:IAA',
    'Job:Lawyer',}
}